/**
 * Compiles the extracted Claude Design templates (lib/design/*.html|css) into
 * lib/design/embedded.ts so the Next.js server bundle carries them without any
 * filesystem access at runtime (required for Netlify serverless functions).
 *
 * Also applies one-time structural transforms to the builder template:
 *  - toolbar action buttons get `data-action` hooks (the design bound them via
 *    `onclick="{{...}}"` placeholders, which we strip)
 *  - a "Create shareable link" button is injected as the primary action
 *  - `<sc-if>` blocks become always-rendered content tagged with `data-if` so
 *    the client can toggle visibility without re-rendering the form
 *  - remaining `on*="{{...}}"` handler placeholders are stripped (the client
 *    uses event delegation on `data-key` / `data-action` attributes instead)
 *
 * The report template is embedded as-is; it contains no event handlers.
 *
 * Run via `npm run embed-design` (wired into predev/prebuild).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (f) => readFileSync(join(root, "lib/design", f), "utf8");

const fontsCss = read("fonts.css");
const baseCss = read("base.css");
const printFixCss = read("print-fix.css");
const reportTpl = read("report.html");
let builderTpl = read("builder.html");

// --- builder transforms -----------------------------------------------------

// 1. Toolbar buttons / inputs -> data-action hooks.
const actionMap = [
  ['onclick="{{doPrint}}"', 'data-action="print"'],
  ['onclick="{{downloadReport}}"', 'data-action="downloadReport"'],
  ['onclick="{{downloadJob}}"', 'data-action="downloadJob"'],
  ['onclick="{{resetAll}}"', 'data-action="resetAll"'],
  ['onchange="{{onLoadJob}}"', 'data-action="loadJob"'],
];
for (const [from, to] of actionMap) {
  if (!builderTpl.includes(from)) {
    throw new Error(`embed-design: expected builder marker not found: ${from}`);
  }
  builderTpl = builderTpl.replace(from, to);
}

// 2. Inject the "Create shareable link" button as the primary toolbar action,
//    styled to match the design's toolbar buttons.
const printBtnIdx = builderTpl.indexOf('<button data-action="print"');
if (printBtnIdx < 0) throw new Error("embed-design: print button not found");
const createLinkBtn =
  `<button data-action="createLink" style="display:inline-flex;align-items:center;gap:7px;` +
  `background:#00BD70;color:#fff;border:none;font:700 12.5px 'Open Sans',sans-serif;` +
  `padding:10px 15px;border-radius:9px;cursor:pointer;">Create shareable link</button> `;
builderTpl =
  builderTpl.slice(0, printBtnIdx) + createLinkBtn + builderTpl.slice(printBtnIdx);

// 3. <sc-if value="{{key}}" ...>CONTENT</sc-if> -> CONTENT with data-if="key"
//    on its first element (client toggles `display` from state).
builderTpl = builderTpl.replace(
  /<sc-if value="\{\{(\w+)\}\}"[^>]*>([\s\S]*?)<\/sc-if>/g,
  (_, key, content) => content.replace(/<(\w+)/, `<$1 data-if="${key}"`),
);

// 4. Strip remaining handler placeholders.
builderTpl = builderTpl.replace(/\son[a-z]+="\{\{[^}]+\}\}"/g, "");

// --- report transforms --------------------------------------------------------

// Mark free-text elements so the fit runtime can shrink them when a job's text
// is longer than the fixed Letter sheet allows (prevents content spilling into
// the footer / off the printed page).
let fittedReportTpl = reportTpl;
for (const key of ["analysis", "diagHeadline", "diagText"]) {
  const re = new RegExp(`(<[a-z][^>]*)(>\\s*\\{\\{${key}\\}\\})`);
  if (!re.test(fittedReportTpl)) {
    throw new Error(`embed-design: fit target {{${key}}} not found in report template`);
  }
  fittedReportTpl = fittedReportTpl.replace(re, `$1 data-fit$2`);
}

// --- emit -------------------------------------------------------------------

const banner =
  "// GENERATED by scripts/embed-design.mjs — do not edit by hand.\n" +
  "// Source of truth: lib/design/{report,builder}.html + {fonts,base}.css\n" +
  "// (extracted from the Claude Design file `MC Scan Report Generator.html`).\n";

const out =
  banner +
  `export const FONTS_CSS = ${JSON.stringify(fontsCss)};\n` +
  `export const BASE_CSS = ${JSON.stringify(baseCss)};\n` +
  `export const PRINT_FIX_CSS = ${JSON.stringify(printFixCss)};\n` +
  `export const REPORT_TPL = ${JSON.stringify(fittedReportTpl)};\n` +
  `export const BUILDER_TPL = ${JSON.stringify(builderTpl)};\n`;

writeFileSync(join(root, "lib/design/embedded.ts"), out);
console.log(
  `embed-design: wrote lib/design/embedded.ts (${(out.length / 1024).toFixed(0)} KiB)`,
);
